# Azure Pipelines for Java project using Gradle Wrapper on Windows with JDK 17

trigger:
  - master

pool:
  vmImage: 'windows-2022'  # Windows environment

steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew.bat'  # Use .bat for Windows
      workingDirectory: '.'
      tasks: 'clean build'
      options: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/build/test-results/test/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'  # Using JDK 17
      jdkArchitectureOption: 'x64'
