pool:
  name: 'Default'

steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew.bat'
      workingDirectory: '.'
      tasks: 'clean build'
      options: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/build/test-results/test/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
